-- MySQL Script generated by MySQL Workbench
-- Sun Jun 19 14:04:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema checdiagrams
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema checdiagrams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `checdiagrams` DEFAULT CHARACTER SET utf8mb3 ;
USE `checdiagrams` ;

-- -----------------------------------------------------
-- Table `checdiagrams`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `birthDate` DATE NULL DEFAULT NULL,
  `address` VARCHAR(60) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `avatar` VARCHAR(45) NULL DEFAULT 'images/avatar/default.png',
  `userroles_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_UserRoles1_idx` (`userroles_id` ASC) INVISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checdiagrams`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shippingCost` DECIMAL(6,2) NOT NULL,
  `discount` INT NULL DEFAULT NULL,
  `total` DECIMAL(6,2) NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Users_id`),
  INDEX `fk_Sales_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `checdiagrams`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checdiagrams`.`detailsales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`detailsales` (
  `id` INT NOT NULL,
  `price` INT NOT NULL,
  `quantity` INT NOT NULL,
  `Sales_id` INT NOT NULL,
  `Sales_Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detailSales_Sales1_idx` (`Sales_id` ASC, `Sales_Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_detailSales_Sales1`
    FOREIGN KEY (`Sales_id` , `Sales_Users_id`)
    REFERENCES `checdiagrams`.`sales` (`id` , `Users_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checdiagrams`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `bitterness` INT NOT NULL,
  `color` INT NOT NULL,
  `alcohol` DECIMAL(6,2) NOT NULL,
  `body` VARCHAR(45) NOT NULL,
  `carbonation` VARCHAR(45) NOT NULL,
  `hop` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL DEFAULT 'Design/540x540.png',
  `category` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `discount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checdiagrams`.`products_has_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`products_has_sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Products_id` INT NOT NULL,
  `detailSales_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Products_id`, `detailSales_id`),
  INDEX `fk_Products_has_Sales_Products1_idx` (`Products_id` ASC) VISIBLE,
  INDEX `fk_Products_has_Sales_detailSales1_idx` (`detailSales_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_Sales_detailSales1`
    FOREIGN KEY (`detailSales_id`)
    REFERENCES `checdiagrams`.`detailsales` (`id`),
  CONSTRAINT `fk_Products_has_Sales_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `checdiagrams`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checdiagrams`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`recipes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `volume` DECIMAL(6,2) NOT NULL,
  `boilvolume` DECIMAL(6,2) NOT NULL,
  `alcohol` DECIMAL(6,2) NOT NULL,
  `targetFG` DECIMAL(6,2) NOT NULL,
  `targetOG` DECIMAL(6,2) NOT NULL,
  `initialPH` DOUBLE NOT NULL,
  `finalPH` DOUBLE NOT NULL,
  `mashTemp` DECIMAL(6,2) NOT NULL,
  `mashTime` DECIMAL(6,2) NOT NULL,
  `boilTime` DECIMAL(6,2) NOT NULL,
  `fermentationTemp` DECIMAL(6,2) NOT NULL,
  `malt1` VARCHAR(45) NOT NULL,
  `malt1Amount` DECIMAL(6,2) NOT NULL,
  `malt2` VARCHAR(45) NULL DEFAULT NULL,
  `malt2Amount` DECIMAL(6,2) NULL DEFAULT NULL,
  `malt3` VARCHAR(45) NULL DEFAULT NULL,
  `malt3Amount` DECIMAL(6,2) NULL DEFAULT NULL,
  `hop1` VARCHAR(45) NOT NULL,
  `hop1Amount` DECIMAL(6,2) NOT NULL,
  `hop1Moment` VARCHAR(45) NULL DEFAULT NULL,
  `hop2` VARCHAR(45) NULL DEFAULT NULL,
  `hop2Amount` DECIMAL(6,2) NULL DEFAULT NULL,
  `hop2Moment` VARCHAR(45) NULL DEFAULT NULL,
  `hop3` VARCHAR(45) NULL DEFAULT NULL,
  `hop3Amount` DECIMAL(6,2) NULL DEFAULT NULL,
  `hop3Moment` VARCHAR(45) NULL DEFAULT NULL,
  `yeast` VARCHAR(45) NOT NULL,
  `yeastAmount` DECIMAL(6,2) NOT NULL,
  `brewerTip` VARCHAR(100) NOT NULL,
  `foodPairing` VARCHAR(100) NOT NULL,
  `users_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checdiagrams`.`shoppingcart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`shoppingcart` (
  `id_Cart` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `discount` DECIMAL(6,2) NULL DEFAULT NULL,
  `shippingCost` INT NOT NULL,
  `total` DECIMAL(18,2) NOT NULL,
  `sold` INT NOT NULL DEFAULT '0',
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id_Cart`),
  INDEX `fk_ShoppingCart_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_ShoppingCart_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `checdiagrams`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checdiagrams`.`shoppingcart_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`shoppingcart_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Products_id` INT NOT NULL,
  `ShoppingCart_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ShoppingCart_Products_Products1_idx` (`Products_id` ASC) VISIBLE,
  INDEX `fk_ShoppingCart_Products_ShoppingCart1_idx` (`ShoppingCart_id` ASC) VISIBLE,
  CONSTRAINT `fk_ShoppingCart_Products_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `checdiagrams`.`products` (`id`),
  CONSTRAINT `fk_ShoppingCart_Products_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_id`)
    REFERENCES `checdiagrams`.`shoppingcart` (`id_Cart`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `checdiagrams`.`userroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `checdiagrams`.`userroles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(45) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`),
  CONSTRAINT `users_id`
    FOREIGN KEY (`id`)
    REFERENCES `checdiagrams`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
